# Generated by Django 4.2.2 on 2023-06-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaTandil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turnoDia', models.DateField()),
                ('turnoHora', models.DateTimeField()),
                ('medico', models.CharField(max_length=40)),
                ('paciente', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='medico',
            name='turnoDia',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='turnoHora',
        ),
    ]
